### PR TITLE
Updated BR authentication service url.

### PR DESCRIPTION
**Pull request by nathan130200**
Mirror1: https://minhaconta.levelupgames.com.br/AuthenticationService.svc
Mirror2: http://auth.warface.levelupgames.com.br/AuthenticationService.svc (do not working yet ERR_CONNECTION_TIMED_OUT )

### CODE REVIEW

**Comment by Levak** [comment]
In the commit you only changed the subdomain of the auth API, but in the commit you mention "salt and token". Did you forgot to commit them? or you know you need to change them but you don't know them?

Said otherwise - Is _this_ commit fully functional to log a bot on BR?
I cannot test myself, non-BR IPs are blocked.

**Comment by nathan130200** [comment]
Not only was the subdomain. I mentioned salt and token because of GetSalt and CreateToken

**Comment by Warpricee** [comment]
como faço pra atualizar  ?

**Comment by Warpricee** [comment]
esse programa nao funciona em windows 7 ?

**Comment by Warpricee** [comment]
@Levak nao pega em windows 7 ?

**Comment by nathan130200** [comment]
@Warpricee pega em todos os sistemas. no caso do windows 7 você precisa baixar a versão mingw em https://github.com/Levak/warfacebot/releases

**Comment by nathan130200** [comment]
@Warpricee o levak é americano :V

**Comment by Levak** [comment]
> @Warpricee o levak é americano: V

Nope, not American, European.

**Comment by nathan130200** [comment]
Lol.

**Pull request merged**
