### PR TITLE
Update cmd_randombox.c

### PR DESCRIPTION
**Pull request by alexalok**
Probably typo?

### CODE REVIEW

**Comment by Levak** [comment]
Tell that to Kiev devs :P

```
 <item name="ar12_gold01_shop" regular="" weight="1" top_prize_token="box_token_cry_money_35" win_limit="1000"/>
```

**Comment by alexalok** [comment]
So, um, exar and r16 have the same counter? Oo

**Comment by Levak** [comment]
Yes, and this is actually problematic, as if you were at 999 on exarl and drop 1 on r16a4, you basically lost the 999 boxes in exarl.

**Comment by alexalok** [comment]
GG then :(

**Comment by alexalok** [comment]
On ru it's fixed BTW
`<item name="ar12_gold01_shop" weight="1" top_prize_token="box_token_cry_money_36" win_limit="1000"/>`

**Pull request closed without merging**
